#!/bin/bash

export XDG_RUNTIME_DIR_WESTON=/tmp/weston-$USER
mkdir -p "$XDG_RUNTIME_DIR_WESTON"
chmod 700 "$XDG_RUNTIME_DIR_WESTON"

for i in {1..40}; do
    candidate="wayland-x11-$i"
    if [[ ! -e "$XDG_RUNTIME_DIR_WESTON/$candidate" ]]; then
        export WAYLAND_DISPLAY="$candidate"
        echo "$@" > "$XDG_RUNTIME_DIR_WESTON/$candidate"
        break
    fi
done

# Echo config on launch
cat > "$XDG_RUNTIME_DIR_WESTON/weston.ini" <<EOL
[core]
idle-time=0
require-input=false
xwayland=true
[shell]
panel-position=none
panel-location=none
background-color=0xff000000
EOL

# if for some reason an app looks better with custom properties
args=()
app_args=()
if [[ "$1" == "google-chrome"* ]]; then
    args+=("--height" "768" "--width" "1024")
    app_args+=("--start-maximized")
elif [[ "$1" == "spotify" ]] || [[ "$1" == "code" ]]; then
    app_args+=("--enable-features=UseOzonePlatform" "--ozone-platform=wayland")
fi

echo "Loading weston on $WAYLAND_DISPLAY..."
XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" weston --config="$XDG_RUNTIME_DIR_WESTON/weston.ini" --backend=x11-backend.so --socket=$WAYLAND_DISPLAY "${args[@]}" > /dev/null 2>&1 & 
WESTON_PID=$!

#while [ ! -S "$XDG_RUNTIME_DIR_WESTON/$WAYLAND_DISPLAY" ]; do
#    sleep 0.2
#done

sleep 0.2 #wait to destroy title?

WESTON_WINID=$(wmctrl -l | grep "Weston Compositor" | awk -F " " '{print $1}' | head -n 1)

if [[ "$1" == "waydroid" ]] && [[ "$2" == "show-full-ui" ]]; then
    wmctrl -r "Weston Compositor - screen0" -b add,maximized_vert,maximized_horz
elif [[ "$WAY11_WINDOW" == "max" ]]; then
    wmctrl -r "Weston Compositor - screen0" -b add,maximized_vert,maximized_horz
fi

# Special app stuff...
if [[ "$1" != "waydroid" ]]; then
    if [[ "$WAY11_HIDECONTROLS" == "1" ]]; then
        xprop -id "$WESTON_WINID" -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0"
    fi
else
    if [[ "$2" != "app" ]]; then
        xprop -id "$WESTON_WINID" -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0"
    fi
fi

# Set app title
#chmod +x ./helpers/set.sh
#./helpers/set.sh "$@" &
# Move to eliminate extra files
set_title() {
    wmctrl -r "Weston Compositor - screen0" -N "$1"
}

if [[ "$1" == "google-chrome"* ]]; then set_title "Google Chrome"
elif [[ "$1" == "epiphany" ]] || [[ "$1" == "epiphany-browser" ]]; then set_title "GNOME Web"
elif [[ "$1" == "waydroid" ]] && [[ "$4" == "com.mojang.minecraftedu" ]]; then set_title "Minecraft Education"
else set_title "$(basename "$1" | sed 's/./\u&/')"
fi

XDG_SESSION_TYPE=wayland GDK_BACKEND=wayland WAYLAND_DISPLAY="$WAYLAND_DISPLAY" "$@" "${app_args[@]}"

# pgrep -f '$@*' | head -n 1

kill -9 "$WESTON_PID"
rm -rf "$XDG_RUNTIME_DIR_WESTON/$candidate"

exit 0
