#!/bin/bash

if [ ! -d "apps" ]; then
	cd "$HOME/way11"
	if [ ! -d "apps" ]; then
		cd "$HOME/.techguy16/way11"
		if [ ! -d "apps" ]; then
			cd "$WAY11_APPSDIR"
			if [ ! -d "apps" ] || [ ! -d "../apps" ]; then
				yad --title="Way11" --center --width=300 --height=50 \
					--text="Could not find app info directory!" --button="OK":0 --borders=10
				exit 0
			fi
		fi
	fi
fi

if [ -e "way11" ]; then
	chmod +x way11
	export WAY11_EXECUTABLE="./way11"
elif [ -x "$(command -v way11)" ]; then
	export WAY11_EXECUTABLE="way11"
else
	yad --title="Way11" --center --width=300 --height=50 \
		--text="Could not find way11 executable!\nPlease reinstall way11." --button="OK":0 --borders=10
	exit 0
fi

apps=()
for i in ./apps/*; do
	if [[ "$i" != *"icons" ]]; then
		name=$(echo $i | cut -d'/' -f3-)
		icon="apps/icons/$name.png"
		apps+=("$icon" "$(echo $i | cut -d'/' -f3-)")
	fi
done

if [[ "$1" == "settings" ]]; then
	pkill -f "yad*"
	
	OPTION1="FALSE"
	if [[ "$WAY11_DISABLECUSTOM" == "1" ]]; then OPTION1="TRUE" 
	fi

	OPTION2="FALSE"
	if [[ "$WAY11_WINDOW" == "max" ]]; then OPTION2="TRUE" 
	fi

	OPTION3="FALSE"
	if [[ "$WAY11_HIDECONTROLS" == "1" ]]; then OPTION3="TRUE" 
	fi

	settings=$(yad --title="way11" --text="<big><b>Current session settings</b></big>" --form \
		--center --height=400 --width=300 \
		--field="Override all custom app settings:CHK" "$OPTION1" \
		--field="Open all apps maximised:CHK" "$OPTION2" \
		--field="Hide all window controls:CHK" "$OPTION3" \
		--field="Window width" "$WAY11_WIDTH" \
		--field="Window height" "$WAY11_HEIGHT")
	
	if [[ "$(echo $settings | awk -F'|' '{print $1}')" == "TRUE" ]]; then
		export WAY11_DISABLECUSTOM=1
	else
		export WAY11_DISABLECUSTOM=0
	fi
	if [[ "$(echo $settings | awk -F'|' '{print $2}')" == "TRUE" ]]; then
		export WAY11_WINDOW=max
	else
		export WAY11_WINDOW=min
	fi
	if [[ "$(echo $settings | awk -F'|' '{print $3}')" == "TRUE" ]]; then
		export WAY11_HIDECONTROLS=1
	else
		export WAY11_HIDECONTROLS=0
	fi
	if [[ "$(echo $settings | awk -F'|' '{print $4}')" != "" ]]; then
		export WAY11_WIDTH="$(echo $settings | awk -F'|' '{print $4}')"
	else
		export WAY11_WIDTH=""
	fi
	if [[ "$(echo $settings | awk -F'|' '{print $5}')" != "" ]]; then
		export WAY11_HEIGHT="$(echo $settings | awk -F'|' '{print $5}')"
	else
		export WAY11_HEIGHT=""
	fi

	./way11-gui
else 
	data=$(yad --title="way11" --center --width=300 --height=400 \
		--text="Select an app from the list below to launch it in way11." \
		--list --icon-size=32 --column="Icon:IMG" --column="App" \
		--button="Settings!open-menu:./way11-gui settings" \
		--button="<b>Execute</b>!go-next:0" \
		--no-headers --image="assets/logo-64.png" --window-icon="assets/logo-64.png" \
		--image-on-top --class="way11" "${apps[@]}")
	EXVAL=$?

	if [ $EXVAL -eq 0 ]; then
		app=$(echo $data | awk -F'|' '{print $2}')
		directory="apps/$app"
		command=$(cat "$directory")
		./way11 $command
	fi
fi